package com.semantyca.mixpla.dto.queue.command;

public enum CommandType {
    FLOW_RESTART,
    SONG_RATED,
    WAKE_UP_DJ,
    GET_SLEEP_DJ,
    REBUILD_AGENDA,
    BACK_PRESSURE_EMISSION,
    AIVOX_INIT_BRAND,
    JESOOS_START_BRAND,
    JESOOS_START_OTS,
    JESOOS_STOP_OTS,
    JESOOS_OTS_FINISHED,
    ANALYZE_BATCH_REQUESTED
}
